jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

spring.datasource.url=${DATABASE_JBDC_URL}
spring.datasource.username=${DATABASE_JBDC_USER}
spring.datasource.password=${DATABASE_JBDC_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
